
function certeza() {
    window.alert('TEM CERTEZA QUE DESEJA CONTINUAR? OS CONTEUDOS DESSE SITE PODEM SER PERTUBADOR. CONVERSE COM UM MEDICO ANTES DE PROSSEGUIR...')
    window.prompt('DIGITE EU ACEITO PARA PROSSEGUIR') 
    window.alert('VOCÊ FOI AVISADO!')
}

